SELECT STUDENT.USN, STUDENT.SName, IAMARKS.FinalIA,
CASE 
    WHEN IAMARKS.FinalIA BETWEEN 17 AND 20 THEN 'Outstanding'
    WHEN IAMARKS.FinalIA BETWEEN 12 AND 16 THEN 'Average'
    WHEN IAMARKS.FinalIA < 12 THEN 'Weak'
END AS CAT
FROM IAMARKS
JOIN CLASS ON IAMARKS.USN = CLASS.USN
JOIN SEMSEC ON CLASS.SSID = SEMSEC.SSID
JOIN STUDENT ON IAMARKS.USN = STUDENT.USN
WHERE SEMSEC.Sem = 8 AND SEMSEC.Sec IN ('A', 'B', 'C');
