SELECT DISTINCT MOVIES.Mov_Title 
FROM MOVIES 
JOIN MOVIE_CAST ON MOVIES.Mov_id = MOVIE_CAST.Mov_id 
WHERE MOVIE_CAST.Act_id IN (
    SELECT Act_id 
    FROM MOVIE_CAST 
    GROUP BY Act_id 
    HAVING COUNT(DISTINCT Mov_id) >= 2
);
